language: python
python:
  - "2.7"

sudo: false

env:
  global:
    - PIP_FIND_LINKS=file://$HOME/.cache/pip
    - PIP_CACHE_DIR=$HOME/.cache/pip
  matrix:
    - TOX_ENV=py27-hg2.6
    - TOX_ENV=py26-hg2.6
    - TOX_ENV=py27-hg3.2

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

before_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis McTravis"
  - cp lib/python/mozilla_buildtools/test/hgrc ~/.hgrc

install:
  - pip install tox==1.9.2

script:
  - tox -e $TOX_ENV
  # Remove logs to avoid cache uploads
  - rm -rf $HOME/.cache/pip/log

after_script:
  - tox -e py27-coveralls
